version: "3.9"

services:
  mysqldb:
    container_name: safahlk/mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /home/mysql/data:/var/lib/mysql


  spring_app:
    image: safahlk/achatbackend
    container_name: achatbackend
    restart: on-failure
    ports:
      - "9090:9090"
    depends_on:
      - mysqldb

