version: "3.3"

services:
  mysqldb:
    container_name: mysql
    image: mysql:5.6
    tty: true
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'achatdb'
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - /home/mysql/data:/var/lib/mysql:rw


  spring_app:
    image: safahlk/achatbackend:latest
    container_name: achatbackend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: achatdb
    restart: on-failure
    ports:
      - '8089:8089'
    links:
      - mysqldb
  angular-app:
      depends_on:
      - spring_app
      image: safahlk/achatfrontend:latest
      container_name: achatfrontend
      ports:
        - 4200:80
      links:
        - spring_app
volumes:
  mysqldb: { }