version: "3"

services:
  mysqldb:
    container_name: mysql
    image: mysql:8
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql/data:/var/lib/mysql


  spring_app:
    image: safahlk/achatbackend
    container_name: achatbackend
    restart: on-failure
    ports:
      - "9090:9090"
    depends_on:
      - mysqldb

